# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-toml
    -   id: check-yaml
    -   id: check-added-large-files
# -   repo: local
#     hooks:
#     - id: generate_docs
#       name: generate_docs
#       entry: typer nstimes.main utils docs --name nstimes --output README.md
#       language: script
#       pass_filenames: false
-   repo: https://github.com/psf/black
    rev: '23.9.1'
    hooks:
    -    id: black
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
    -   id: reorder-python-imports
